/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_vandertil_jerasure_jni_Decoding */

#ifndef _Included_eu_vandertil_jerasure_jni_Decoding
#define _Included_eu_vandertil_jerasure_jni_Decoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_vandertil_jerasure_jni_Decoding
 * Method:    decodeWithMatrix
 * Signature: (III[IZ[I[[B[[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_vandertil_jerasure_jni_Decoding_decodeWithMatrix
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jboolean, jintArray, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
